apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: prod
  name: prod_admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
subjects:
- kind: User
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io